language: go

install:
  - mkdir ~/bin
  - wget https://github.com/gohugoio/hugo/releases/download/v0.26/hugo_0.26_Linux-64bit.tar.gz -O hugo.tgz
  - tar xfv hugo.tgz -C bin
  - rm hugo.tgz bin/*.md
  - export PATH=$HOME/bin:$PATH

script:
  - hugo

deploy:
  theme: herring-cove
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  on:
    branch: master
