language: go

install:
  - go install github.com/gohugoio/hugo

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: $HOME/gopath/src/github.com/localanu/VirtualMonitor-hugo.github.io
  target_branch: gh-pages
  on:
    branch: master
